### PR TITLE
Fix/armour standard prefix paths

### LINKED ISSUE #493: update armour_standard prefix

### PR DESCRIPTION
**Pull request by OverYandere**
Refactors all internal paths for armour standard. Closes #493

### CODE REVIEW

File: addons/armour_standard/data/marines2/arid/config_weapons.hpp [hunk 1]
```diff
@@ -63,532 +63,3 @@ class 34thPRC_ArmourStandard_Marines2_CH252_Arid_EyePiece_Blue : 34thPRC_ArmourS
 		eyewear_color = "blue";
 	};
 };
-class 34thPRC_ArmourStandard_Marines2_CH252_Arid_EyePiece_Orange : 34thPRC_ArmourStandard_Marines2_CH252_Urban_EyePiece
```
Comment (Lupus590) [inline addons/armour_standard/data/marines2/arid/config_weapons.hpp:66]: Why is this gone?

**Review by Lupus590 — CHANGES_REQUESTED** [review]

**Review by Lupus590 — CHANGES_REQUESTED** [review]
image
image
Multiple eye peices possibly broken? Custom helmets only?
Again custom helmets: 
image
RVMAT? 
image
All of the ODST helmets
image

**Review by Lupus590 — COMMENTED** [review]
Customs again: 
image
Inheritance might be wrong for the custom shoulderless uniforms

**Review by Lupus590 — COMMENTED** [review]
custom armour again image
And some of the standard odst vests too
image
image

**Review by Lupus590 — CHANGES_REQUESTED** [review]
image
image

**Review by Lupus590 — APPROVED** [review]
Missing chin strap on custom armour, can be fixed with custom armour pbo patch (visor and eyepiece are also still broken for custom armour but that can also be fixed in that pbo patch)
image
